# -*- coding: utf-8 -*-
"""DAT_402_Project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_oNxnM8Hwv9KW2bkNtNvOu9y6ThcKGq
"""

from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/My Drive/Colab Notebooks/Datafiles/project_1_data.csv"


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(path)
df = df.rename(columns={
    'Year': 'year',
    'TOTAL FAMILY INCOM': 'family_income',
    'AMT INVESTED IN STOCKS ': 'stocks',
    'AMOUNT CREDIT/STORE CARD DEBT': 'credit_debt',
    ' COMPLETED ED': 'education'
})

df.fillna(0, inplace=True)

# covid grouping
df['period'] = df['year'].apply(lambda y: 'Pre-COVID' if y <= 2019 else 'Post-COVID')

summary = (
    df.groupby('period')[['family_income', 'stocks']]
    .agg(['mean', 'median'])
    .reset_index()
)

summary.columns = ['period', 'income_mean', 'income_median', 'stocks_mean', 'stocks_median']
print(summary)

palette = ['skyblue', 'lightgreen']

# avg and median plot
plt.figure(figsize=(8,5))
summary_melt_income = summary.melt(id_vars='period', value_vars=['income_mean','income_median'],
                                   var_name='stat', value_name='value')
sns.barplot(x='period', y='value', hue='stat', data=summary_melt_income, palette=palette, order=['Pre-COVID', 'Post-COVID'])
plt.title("Average vs Median Family Income (Pre vs Post COVID)")
plt.ylabel("Family Income")
plt.xlabel("")
plt.legend(title="")
plt.show()

# investment plot
palette = ['skyblue', 'lightgreen']
plt.figure(figsize=(8,5))
summary_melt_stocks = summary.melt(id_vars='period', value_vars=['stocks_mean','stocks_median'],
                                   var_name='stat', value_name='value')
sns.barplot(x='period', y='value', hue='stat', data=summary_melt_stocks, palette=palette,  order=['Pre-COVID', 'Post-COVID'])
plt.title("Average vs Median Stock Investments (Pre vs Post COVID)")
plt.ylabel("Stock Investments")
plt.xlabel("")
plt.legend(title="")
plt.show()

# Line chart by year
yearly = (
    df.groupby('year')[['family_income','stocks']]
    .agg(['mean','median'])
    .reset_index()
)
yearly.columns = ['year','income_mean','income_median','stocks_mean','stocks_median']

fig, ax = plt.subplots(1,2, figsize=(12,5), sharex=True)
sns.lineplot(x='year', y='income_mean', data=yearly, ax=ax[0], marker='o', label='Mean')
sns.lineplot(x='year', y='income_median', data=yearly, ax=ax[0], marker='s', label='Median')
ax[0].set_title("Family Income Over Time")
ax[0].set_ylabel("Family Income")

sns.lineplot(x='year', y='stocks_mean', data=yearly, ax=ax[1], marker='o', label='Mean')
sns.lineplot(x='year', y='stocks_median', data=yearly, ax=ax[1], marker='s', label='Median')
ax[1].set_title("Stock Investments Over Time")
ax[1].set_ylabel("Stock Investments")

plt.tight_layout()
plt.show()

df.isnull().sum()

#tp80

df['net_wealth'] = df['family_income'].fillna(0) + df['stocks'].fillna(0) - df['credit_debt'].fillna(0)


tp80 = df['net_wealth'].quantile(0.8)
print(f"Top 20% (TP80) threshold: {tp80:,.2f}")


df['high_wealth'] = (df['net_wealth'] > tp80).astype(int)

print(df['high_wealth'].value_counts(normalize=True))
print(df[['year', 'family_income', 'stocks', 'credit_debt', 'net_wealth', 'high_wealth']].head(10))

#share wealth plot
import seaborn as sns
import matplotlib.pyplot as plt

df['period'] = df['year'].apply(lambda y: 'Pre-COVID' if y <= 2019 else 'Post-COVID')

sns.barplot(x='period', y='high_wealth', data=df, estimator=lambda x: 100*sum(x)/len(x))
plt.ylabel("% High Wealth Households")
plt.title("Share of High-Wealth Households Pre vs Post COVID")
plt.show()

#summary wealth groups

summary = df.groupby('period')['high_wealth'].agg(
    count='count',
    high_wealth_households='sum'
)
summary['pct_high_wealth'] = 100 * summary['high_wealth_households'] / summary['count']

print(summary)

#new df and tp80 and tp95 thresholds

df2 = pd.read_csv(path)
df2 = df2.rename(columns={
    'Year': 'year',
    'TOTAL FAMILY INCOM': 'family_income',
    'AMT INVESTED IN STOCKS ': 'stocks',
    'AMOUNT CREDIT/STORE CARD DEBT': 'credit_debt',
    ' COMPLETED ED': 'education'
})
df2.fillna(0, inplace=True)
df2['net_wealth'] = df2['family_income'] + df2['stocks'] - df2['credit_debt']


tp80 = df2['net_wealth'].quantile(0.8)
tp95 = df2['net_wealth'].quantile(0.95) # Corrected typo from 'net_weath' to 'net_wealth'
print(f"Top 20% (TP80) threshold: {tp80:,.2f}")
print(f"Top 5% (TP95) threshold: {tp95:,.2f}")
df2['high_wealth'] = (df2['net_wealth'] > tp80).astype(int) # Changed df to df2

feature_cols =  df2.drop(columns=['high_wealth'])
X = df2.drop(columns=['high_wealth'])
y = df2.high_wealth

#tp95 and tp80 wealth percent dif

tp95_net_wealth = df.groupby('period')['net_wealth'].quantile(0.95).rename('tp95_net_wealth')
tp95_income = df.groupby('period')['family_income'].quantile(0.95).rename('tp95_income')

tp95_table = pd.concat([tp95_income, tp95_net_wealth], axis=1).reset_index()
print("95th Percentile Summary by Period")
print(tp95_table)

tp80_net_wealth = df.groupby('period')['net_wealth'].quantile(0.8).rename('tp80_net_wealth')
tp80_income = df.groupby('period')['family_income'].quantile(0.8).rename('tp80_income')

tp80_table = pd.concat([tp80_income, tp80_net_wealth], axis=1).reset_index()
print("80th Percentile Summary by Period")
print(tp80_table)

tp95_pre = tp95_table.set_index('period').loc['Pre-COVID', 'tp95_net_wealth']
tp95_post = tp95_table.set_index('period').loc['Post-COVID', 'tp95_net_wealth']
tp95_percent_diff = 100 * (tp95_post - tp95_pre) / tp95_pre
print(f"TP95 net_wealth % change  {tp95_percent_diff:.2f}%")

tp80_pre = tp80_table.set_index('period').loc['Pre-COVID', 'tp80_net_wealth']
tp80_post = tp80_table.set_index('period').loc['Post-COVID', 'tp80_net_wealth']
tp80_percent_diff = 100 * (tp80_post - tp80_pre) / tp80_pre
print(f"TP80 net_wealth % change  {tp80_percent_diff:.2f}%")

# wealth percentiles
percentiles = [0.5, 0.8, 0.95]

nw_percentiles = (
    df.groupby('year')['net_wealth']
      .quantile(percentiles)
      .unstack(level=1)
      .rename(columns={0.5: 'P50', 0.8: 'P80', 0.95: 'P95'})
      .reset_index()
)

print("\n=== Net Wealth Percentiles by Year ===")
print(nw_percentiles)

plt.figure(figsize=(8, 5))
for col in ['P50', 'P80', 'P95']:
    plt.plot(nw_percentiles['year'], nw_percentiles[col], marker='o', label=col)

plt.xlabel('Year')
plt.ylabel('Net Wealth')
plt.title('Net Wealth Percentiles Over Time')
plt.legend()
plt.tight_layout()
plt.show()

#logistic
from sklearn.preprocessing import  StandardScaler
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_standardized, y, test_size = 0.2, random_state = 0)

df['high_wealth'].value_counts()

from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

importance = logreg.coef_[0]
pd.DataFrame(importance, index= feature_cols.columns, columns=["Coefficients"])

y_pred = logreg.predict(X_test)
y_pred

from sklearn import metrics
cf_matrix = metrics.confusion_matrix(y_test, y_pred)
cf_matrix

import seaborn as sns
import matplotlib.pyplot as plt

cf_matrix = metrics.confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=['0', '1'],
            yticklabels=[ '0',  '1'])
plt.title("Regression Confusion Matrix")
plt.ylabel("Labels")
plt.xlabel("Predicted")
plt.show()

print("Logistic Regression Test Accuracy:{:.3f}".format(metrics.accuracy_score(y_test, y_pred)))
print("Logistic Regression Train Accuracy:{:.3f}".format(metrics.accuracy_score(y_train, logreg.predict(X_train))))

from sklearn.model_selection import cross_val_score
print("Logistic Regression Cross Validation: {:.3f}".format(cross_val_score(logreg, X_train, y_train, cv=10).mean()))

logreg.predict_proba(X_test)

y_pred_proba = logreg.predict_proba(X_test)[:,1]

fpr,tpr,thresholds = metrics.roc_curve(y_test, y_pred_proba)
auc = metrics.roc_auc_score(y_test, y_pred_proba)

from matplotlib import pyplot
pyplot.plot(fpr, tpr, label = "Logistic Regression AUC = " +str(auc))
pyplot.xlabel('False Positive Rate')
pyplot.ylabel('True Positive Rate')
pyplot.title('Logistic Regression')
pyplot.legend()
pyplot.plot([0,1],
            [0,1],
            linestyle = '--',
            color = (0.6,0.6,0.6),
            label = "random guessing")

#knn
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

from sklearn import metrics

cf_matrix_knn = metrics.confusion_matrix(y_test, y_pred_knn)

plt.figure(figsize=(6,4))
sns.heatmap(cf_matrix_knn, annot=True, fmt='d', cmap='Greens',
            xticklabels=['0', '1'],
            yticklabels=['0', '1'])
plt.title("KNN Confusion Matrix ")
plt.ylabel("Labels")
plt.xlabel("Predicted")
plt.show()

print("KNN Test Accuracy:{:.3f}".format(metrics.accuracy_score(y_test, y_pred_knn)))
print("KNN Train Accuracy:{:.3f}".format(metrics.accuracy_score(y_train, knn.predict(X_train))))

from sklearn.model_selection import cross_val_score
print("KNN Cross Validation: {:.3f}".format(cross_val_score(knn, X_train, y_train, cv=10).mean()))

y_pred_proba_knn = knn.predict_proba(X_test)[:,1]

fpr_knn, tpr_knn, thresholds_knn = metrics.roc_curve(y_test, y_pred_proba_knn)
auc_knn = metrics.roc_auc_score(y_test, y_pred_proba_knn)

pyplot.plot(fpr_knn, tpr_knn, label = "KNN AUC = " + str(auc_knn))
pyplot.xlabel('False Positive Rate')
pyplot.ylabel('True Positive Rate')
pyplot.title('KNN')
pyplot.legend()
pyplot.plot([0,1],[0,1], linestyle='--', color=(0.6,0.6,0.6))

from sklearn.svm import SVC

svm = SVC(kernel='rbf', probability=True, random_state=0)
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

cf_matrix_svm = metrics.confusion_matrix(y_test, y_pred_svm)

plt.figure(figsize=(6,4))
sns.heatmap(cf_matrix_svm, annot=True, fmt='d', cmap='Purples',
            xticklabels=['0', '1'],
            yticklabels=['0', '1'])
plt.title("SVM Confusion Matrix")
plt.ylabel("Labels")
plt.xlabel("Predicted")
plt.show()

print("SVM Test Accuracy:{:.3f}".format(metrics.accuracy_score(y_test, y_pred_svm)))
print("SVM Train Accuracy:{:.3f}".format(metrics.accuracy_score(y_train, svm.predict(X_train))))

print("SVM Cross Validation:", cross_val_score(svm, X_train, y_train, cv=10).mean())

y_pred_proba_svm = svm.predict_proba(X_test)[:,1]

fpr_svm, tpr_svm, thresholds_svm = metrics.roc_curve(y_test, y_pred_proba_svm)
auc_svm = metrics.roc_auc_score(y_test, y_pred_proba_svm)

pyplot.plot(fpr_svm, tpr_svm, label = "SVM AUC = " + str(auc_svm))
pyplot.xlabel('False Positive Rate')
pyplot.ylabel('True Positive Rate')
pyplot.title('SVM')
pyplot.legend()
pyplot.plot([0,1],
            [0,1],
            linestyle='--',
            color=(0.6,0.6,0.6))